### ISSUE TITLE
Typo in 101_ia.tph

### ISSUE THREAD

**Issue by Salk73** [SpellholdStudios/1pp#5]
I think there is a typo at line 48:

ACTION_IF (**is** iwd) BEGIN // GAME_IS ~totlm how~

ACTION_IF (**GAME_IS** iwd) BEGIN // GAME_IS ~totlm how~

**Comment by GwendolyneFreddy** [comment]
Good catch, but the correct command is

ACTION_IF (is_iwd) BEGIN

is_iwd being a variable defined in ALWAYS library.

Will fix it.

Thanks.

**Comment by Salk73** [comment]
My pleasure.

Keep up your excellent work!
